version: '3.4'

services:
  btsearch:
    image: ${DOCKER_REGISTRY}btsearch
    build:
      context: .
      dockerfile: BTSearch/Dockerfile
  db:
    image: "microsoft/mssql-server-linux"
    environment:
      SA_PASSWORD: "~!@abc456"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"